language: r
cache: packages
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
after_failure:
  - ./travis-tool.sh dump_logs
r_packages:
  - testthat
  - XML
  - base64enc
  - rmarkdown
  - stringi
  - jsonlite
  - httpuv
  - htmlwidgets
  - openssl
  - visNetwork
warnings_are_errors: true
